db:
  image: couchdb
  ports:
    - "5990:5984"
  environment:
    - COUCHDB_USER=admin
    - COUCHDB_PASSWORD=admin
  volumes:
    - ./db/data:/opt/couchdb/data
    - ./db/conf:/opt/couchdb/etc/local.d
